# Явно указываем версию конфига
version: 1.64.2

# Новые параметры вместо устаревших run.*
issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_mock\\.go$"
  uniq-by-line: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

  linters:
    disable-all: true
    enable:
      - gosimple
      - govet
      - staticcheck
      - unused
      - errcheck
      - gofmt
      - goimports

    linters-settings:
      gosimple:
        checks: ["all"]
      errcheck:
        ignore: fmt:.*
      goimports:
        # local-prefixes: github.com/yourname/banner_service_go

  issues:
    exclude-use-default: true
    max-issues-per-linter: 50
    max-same-issues: 10
    exclude:
      - "G104" # Игнорировать необработанные ошибки
      - "G204" # Subprocess launched with variable
    exclude-rules:
      - path: _test\.go
        linters:
          - errcheck
      - path: internal/goarch
        linters:
          - govet
          - staticcheck
          - unused
