FROM nginx:alpine

# Копируем статические файлы
COPY frontend/ /usr/share/nginx/html/

# Копируем кастомную конфигурацию nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]