services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    container_name: go-backend
    restart: unless-stopped
    environment:
      - GIN_MODE=release
      - PORT=8080
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    container_name: go-frontend
    restart: unless-stopped
    ports:
      - "3000:80" # Убираем конфликт с Caddy
    depends_on:
      - backend
    networks:
      - app-network

  caddy:
    image: caddy:2-alpine
    container_name: caddy-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      - backend
      - frontend

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
